language: python
python:
  - 3.6
install:
  - pip install codecov
  - pip install colorama
  - pip install pycodestyle
script:
  - coverage run test_Hangman.py
  - pycodestyle
after_success:
  - codecov
